id = "lucasoe/nix-status"
name = "Nix Status"
version = "0.1.0"
min_noctalia = "5.0.0"
author = "LucasOe"
license = "MIT"
icon = "snowflake"
description = "Widget showing nixpkgs status."
tags = ["nixos", "nix", "bar", "widget"]

[[widget]]
id = "nix-status"
entry = "widget.luau"

	[[widget.setting]]
	key = "hide"
	type = "boolean"
	label = "Hide When up-to-date"
	description = "Hide the widget when nixpkgs is up-to-date"
	default = false
